services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inkrepublik-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Inkrepublik!Dev2026"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - inkrepublik-sqlserver-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  inkrepublik-sqlserver-data: