<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Inkrepublik.Domain\Inkrepublik.Domain.csproj" />
    <ProjectReference Include="..\Inkrepublik.Data\Inkrepublik.Data.csproj" />
    <ProjectReference Include="..\Inkrepublik.Services\Inkrepublik.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>f7d910de-4b62-4218-ac8a-e96acc925c84</UserSecretsId>
  </PropertyGroup>

</Project>
